from lib.mode  import APP_INSTALL as TEST_MODE
MODE = TEST_MODE

PKG_NUM = 50
PKG_START = 40
USER_START = 40
DRIVER_START = 40
DRIVER_NUM = 10

FRONTEND_PORT = 9001

CLI_PORT = 4342
SRV_PORT = 4343
TEST_ROUNDS = 10
MANAGER_PORTS = [10001]

CLIENTS = 1
IFACE = 'lo'

USER = 'user4'
VERSION = '1.0.4'
CATEGORY = '0'
PACKAGE = 'cat0_bbb3'
DRIVER_PACKAGE = 'driver4'
PASSWORD = '123456'
EMAIL = 'user@gmail.com'

LOG_ERROR = True
LOG_DEBUG = True
SHOW_TIME = False
