from lib.mode  import DRV_INSTALL as TEST_MODE
MODE = TEST_MODE

PKG_NUM = 80
PKG_START = 0
USER_START = 0
DRIVER_START = 0
DRIVER_NUM = 160

FRONTEND_PORT = 9001
FRONTEND_SERVERS = ['0.0.0.0']

CLI_PORT = 4342
SRV_PORT = 4343
TEST_ROUNDS = 100
MANAGER_PORTS = [10001]
MANAGER_SERVERS = ['0.0.0.0']
SRV_ADDR = '0.0.0.0'

CLIENTS = 16
IFACE = 'eth0'

USER = 'user'
VERSION = '0.0.1'
CATEGORY = '0'
PACKAGE = 'cat0_pkg'
DRIVER_PACKAGE = 'driver'
PASSWORD = '123456'
EMAIL = 'user@gmail.com'

LOG_ERROR = True
LOG_DEBUG = True
SHOW_TIME = False
